import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import casesRouter from "./cases";
import dashboardRouter from "./dashboard";
import connectorsRouter from "./connectors";
import automationRouter from "./automation";
import preferencesRouter from "./preferences";
import openaiRouter from "./openai";
import batchesRouter from "./batches";
import alertsRouter from "./alerts";
import kbRouter from "./kb";
import vaultRouter from "./vault";
import environmentRouter from "./environment";
import analyticsRouter from "./analytics";
import remoteRouter from "./remote";
import hostingRouter from "./hosting";
import screenshareRouter from "./screenshare";
import companyVaultRouter from "./companyVault";
import recommendRouter from "./recommend";
import securityRouter from "./security";
import pmoRouter from "./pmo";
import stackRouter from "./stack";
import adminRouter from "./admin";
import demoRouter from "./demo";
import builderRouter from "./builder";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(casesRouter);
router.use(dashboardRouter);
router.use(connectorsRouter);
router.use(automationRouter);
router.use(preferencesRouter);
router.use(openaiRouter);
router.use(batchesRouter);
router.use(alertsRouter);
router.use(kbRouter);
router.use(vaultRouter);
router.use(environmentRouter);
router.use(analyticsRouter);
router.use(remoteRouter);
router.use(hostingRouter);
router.use(screenshareRouter);
router.use(companyVaultRouter);
router.use(recommendRouter);
router.use(securityRouter);
router.use(pmoRouter);
router.use(stackRouter);
router.use(adminRouter);
router.use(demoRouter);
router.use(builderRouter);

export default router;
