import { useState, useEffect, useCallback } from "react";
import { Card, Button } from "@/components/ui";
import { motion } from "framer-motion";
import {
  Brain, CheckCircle2, AlertTriangle, Lightbulb, ArrowRight,
  Layers, BarChart3, Zap, RefreshCw, Wifi, WifiOff, Camera
} from "lucide-react";
import { useApiBase } from "@/hooks/use-api-base";
import { Link } from "wouter";

interface Recommendation {
  category: string;
  title: string;
  priority: "critical" | "high" | "medium" | "low";
  rationale: string;
  action: string;
  estimatedImpact: string;
}

interface ConnectorSummary {
  name: string;
  status: string;
  uptime: number;
  totalChecks: number;
}

interface StackData {
  hasSnapshot: boolean;
  snapshotAge: number | null;
  connectors: ConnectorSummary[];
  kbDomains: string[];
  recommendations: Recommendation[];
  stackHealth: { score: number; summary: string };
  topGaps: string[];
  error?: string;
}

const PRIORITY_COLORS: Record<string, string> = {
  critical: "bg-rose-500/10 text-rose-400 border-rose-500/20",
  high:     "bg-orange-500/10 text-orange-400 border-orange-500/20",
  medium:   "bg-amber-500/10 text-amber-400 border-amber-500/20",
  low:      "bg-slate-500/10 text-slate-400 border-slate-500/20",
};

const PRIORITY_ORDER: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3 };

export default function StackIntelligence() {
  const apiBase = useApiBase();
  const [data, setData]             = useState<StackData | null>(null);
  const [loading, setLoading]       = useState(true);
  const [filter, setFilter]         = useState<"all" | "critical" | "high" | "medium" | "low">("all");
  const [capturing, setCapturing]   = useState(false);
  const [captureMsg, setCaptureMsg] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`${apiBase}/api/stack/intelligence`, { credentials: "include" });
      if (res.ok) setData(await res.json() as StackData);
    } finally { setLoading(false); }
  }, [apiBase]);

  const captureSnapshot = async () => {
    setCapturing(true); setCaptureMsg("");
    try {
      const snapshot = {
        userAgent: navigator.userAgent,
        platform: navigator.platform,
        language: navigator.language,
        screenWidth: window.screen.width,
        screenHeight: window.screen.height,
        timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
        cores: navigator.hardwareConcurrency ?? null,
        memory: (navigator as { deviceMemory?: number }).deviceMemory ?? null,
      };
      const res = await fetch(`${apiBase}/api/environment/snapshot`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ snapshot }),
        credentials: "include",
      });
      if (res.ok) {
        setCaptureMsg("Snapshot captured! Re-analyzing stack…");
        void load();
      } else {
        setCaptureMsg("Snapshot failed. Please try again.");
      }
    } catch {
      setCaptureMsg("Network error. Please try again.");
    } finally {
      setCapturing(false);
    }
  };

  useEffect(() => { void load(); }, [load]);

  const scoreColor = !data ? "text-slate-400"
    : data.stackHealth.score >= 80 ? "text-emerald-400"
    : data.stackHealth.score >= 50 ? "text-amber-400" : "text-rose-400";

  const filtered = (data?.recommendations || [])
    .filter(r => filter === "all" || r.priority === filter)
    .sort((a, b) => (PRIORITY_ORDER[a.priority] ?? 99) - (PRIORITY_ORDER[b.priority] ?? 99));

  return (
    <div className="max-w-6xl mx-auto">
      <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8 flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-display font-bold text-white text-glow">Stack Intelligence</h1>
          <p className="text-slate-500 mt-1">Live recommendations generated by Apphia from your real environment data.</p>
        </div>
        <div className="flex items-center gap-2">
          <Button variant="outline" onClick={() => void captureSnapshot()} disabled={capturing || loading} size="sm" className="flex items-center gap-2">
            <Camera className={`w-4 h-4 ${capturing ? "animate-pulse" : ""}`} />
            {capturing ? "Capturing…" : "Capture Snapshot"}
          </Button>
          <Button variant="outline" onClick={() => void load()} disabled={loading} size="sm" className="flex items-center gap-2">
            <RefreshCw className={`w-4 h-4 ${loading ? "animate-spin" : ""}`} />
            Re-analyze
          </Button>
        </div>
      </motion.div>

      {/* Status strip */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">
        {[
          { label: "Stack Health", val: loading ? "—" : `${data?.stackHealth.score ?? 0}/100`, color: scoreColor },
          { label: "Connectors", val: loading ? "—" : String(data?.connectors.length ?? 0), color: "text-sky-400" },
          { label: "Recommendations", val: loading ? "—" : String(data?.recommendations.length ?? 0), color: "text-violet-400" },
          { label: "Snapshot", val: loading ? "—" : data?.hasSnapshot ? `${data.snapshotAge ?? 0}m ago` : "Missing", color: data?.hasSnapshot ? "text-emerald-400" : "text-amber-400" },
        ].map(({ label, val, color }) => (
          <Card key={label} className="p-4 bg-[#0d0f17] border border-white/[0.06]">
            <p className="text-xs text-slate-500 uppercase tracking-wide mb-1">{label}</p>
            <p className={`text-2xl font-bold ${color}`}>{val}</p>
          </Card>
        ))}
      </div>

      {captureMsg && (
        <div className={`mb-4 px-4 py-2.5 rounded-xl text-sm border ${captureMsg.includes("captured") ? "bg-emerald-500/10 border-emerald-500/20 text-emerald-400" : "bg-rose-500/10 border-rose-500/20 text-rose-400"}`}>
          {captureMsg}
        </div>
      )}

      {/* No snapshot notice */}
      {!loading && !data?.hasSnapshot && (
        <Card className="p-6 mb-6 bg-amber-500/5 border border-amber-500/20">
          <div className="flex items-start gap-4">
            <Camera className="w-8 h-8 text-amber-400 shrink-0 mt-0.5" />
            <div className="flex-1">
              <h3 className="font-semibold text-amber-300 mb-1">No Environment Snapshot Captured</h3>
              <p className="text-sm text-slate-400">Capture a snapshot to unlock fully personalized stack analysis. Without it, recommendations are based on connected systems only.</p>
              <Link href="/settings">
                <Button size="sm" className="mt-3" variant="outline">Go to Settings → Capture Snapshot</Button>
              </Link>
            </div>
          </div>
        </Card>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Recommendations list */}
        <div className="lg:col-span-2 space-y-4">
          <div className="flex items-center justify-between">
            <h3 className="text-sm font-semibold text-slate-300">
              Apphia Recommendations {filtered.length > 0 && <span className="text-slate-500 font-normal">({filtered.length})</span>}
            </h3>
            <div className="flex gap-1">
              {(["all","critical","high","medium","low"] as const).map(f => (
                <button key={f} onClick={() => setFilter(f)}
                  className={`px-2.5 py-1 rounded text-xs font-medium transition-colors ${filter === f ? "bg-violet-600 text-white" : "text-slate-500 hover:text-slate-300"}`}>
                  {f === "all" ? "All" : f.charAt(0).toUpperCase() + f.slice(1)}
                </button>
              ))}
            </div>
          </div>

          {loading ? (
            <div className="space-y-3">{[...Array(4)].map((_, i) => <div key={i} className="h-28 bg-white/[0.04] rounded-xl animate-pulse" />)}</div>
          ) : filtered.length === 0 ? (
            <Card className="p-10 text-center bg-[#0d0f17] border border-white/[0.06]">
              <Brain className="w-10 h-10 text-slate-600 mx-auto mb-3" />
              <p className="text-slate-400 text-sm">
                {data?.recommendations.length === 0
                  ? "No recommendations yet. Connect systems or capture an environment snapshot to begin analysis."
                  : "No recommendations at this priority level."}
              </p>
            </Card>
          ) : (
            <div className="space-y-3">
              {filtered.map((rec, i) => (
                <motion.div key={i} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: i * 0.05 }}>
                  <Card className="p-5 bg-[#0d0f17] border border-white/[0.06] hover:border-white/[0.12] transition-colors">
                    <div className="flex items-start justify-between gap-3 mb-2">
                      <div className="flex items-center gap-2 flex-1 min-w-0">
                        <Lightbulb className="w-4 h-4 text-amber-400 shrink-0" />
                        <span className="text-sm font-semibold text-white">{rec.title}</span>
                      </div>
                      <div className="flex gap-2 shrink-0">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${PRIORITY_COLORS[rec.priority]}`}>
                          {rec.priority.toUpperCase()}
                        </span>
                        <span className="text-[10px] text-slate-500 bg-white/[0.04] px-2 py-0.5 rounded-full">{rec.category}</span>
                      </div>
                    </div>
                    <p className="text-xs text-slate-400 mb-3 leading-relaxed">{rec.rationale}</p>
                    <div className="flex items-start gap-2 bg-white/[0.03] rounded-lg p-3 mb-2">
                      <ArrowRight className="w-3.5 h-3.5 text-violet-400 shrink-0 mt-0.5" />
                      <p className="text-xs text-slate-300">{rec.action}</p>
                    </div>
                    {rec.estimatedImpact && (
                      <div className="flex items-center gap-1.5">
                        <Zap className="w-3 h-3 text-emerald-400" />
                        <span className="text-xs text-emerald-400">{rec.estimatedImpact}</span>
                      </div>
                    )}
                  </Card>
                </motion.div>
              ))}
            </div>
          )}
        </div>

        {/* Right sidebar */}
        <div className="space-y-4">
          <Card className="p-5 bg-[#0d0f17] border border-white/[0.06]">
            <h3 className="text-sm font-semibold text-slate-300 mb-3 flex items-center gap-2">
              <BarChart3 className="w-4 h-4" /> Stack Health
            </h3>
            {loading ? <div className="h-20 bg-white/[0.04] rounded animate-pulse" /> : (
              <>
                <div className="flex items-end gap-2 mb-2">
                  <span className={`text-4xl font-bold ${scoreColor}`}>{data?.stackHealth.score}</span>
                  <span className="text-slate-500 mb-1">/ 100</span>
                </div>
                <p className="text-xs text-slate-400 leading-relaxed">{data?.stackHealth.summary}</p>
              </>
            )}
          </Card>

          {(data?.topGaps || []).length > 0 && (
            <Card className="p-5 bg-[#0d0f17] border border-white/[0.06]">
              <h3 className="text-sm font-semibold text-slate-300 mb-3 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4 text-amber-400" /> Top Gaps
              </h3>
              <div className="space-y-2">
                {data?.topGaps.map((g, i) => (
                  <div key={i} className="flex items-start gap-2 text-xs text-slate-400">
                    <span className="w-4 h-4 rounded-full bg-amber-500/10 text-amber-400 flex items-center justify-center text-[9px] font-bold shrink-0 mt-0.5">{i + 1}</span>
                    {g}
                  </div>
                ))}
              </div>
            </Card>
          )}

          <Card className="p-5 bg-[#0d0f17] border border-white/[0.06]">
            <h3 className="text-sm font-semibold text-slate-300 mb-3 flex items-center gap-2">
              <Layers className="w-4 h-4" /> Connected Systems
            </h3>
            {loading ? <div className="h-24 bg-white/[0.04] rounded animate-pulse" /> : (data?.connectors || []).length === 0 ? (
              <div className="text-center py-4">
                <WifiOff className="w-6 h-6 text-slate-600 mx-auto mb-2" />
                <p className="text-xs text-slate-500">No connectors yet.</p>
                <Link href="/connectors">
                  <span className="text-xs text-violet-400 hover:underline cursor-pointer">Set up connectors →</span>
                </Link>
              </div>
            ) : (
              <div className="space-y-2">
                {data?.connectors.map(c => (
                  <div key={c.name} className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      {c.status === "healthy"
                        ? <Wifi className="w-3.5 h-3.5 text-emerald-400" />
                        : <WifiOff className="w-3.5 h-3.5 text-rose-400" />}
                      <span className="text-xs text-slate-400 truncate">{c.name}</span>
                    </div>
                    <span className={`text-xs font-medium ${c.uptime >= 95 ? "text-emerald-400" : c.uptime >= 80 ? "text-amber-400" : "text-rose-400"}`}>{c.uptime}%</span>
                  </div>
                ))}
              </div>
            )}
          </Card>

          {(data?.kbDomains || []).length > 0 && (
            <Card className="p-5 bg-[#0d0f17] border border-white/[0.06]">
              <h3 className="text-sm font-semibold text-slate-300 mb-3 flex items-center gap-2">
                <Brain className="w-4 h-4" /> KB Domains Consulted
              </h3>
              <div className="flex flex-wrap gap-1.5">
                {data?.kbDomains.map(d => (
                  <span key={d} className="text-[10px] px-2 py-0.5 rounded-full bg-violet-500/10 text-violet-400 border border-violet-500/20">{d}</span>
                ))}
              </div>
            </Card>
          )}

          {data?.error && (
            <Card className="p-4 bg-rose-500/5 border border-rose-500/20">
              <div className="flex items-start gap-2">
                <AlertTriangle className="w-4 h-4 text-rose-400 shrink-0 mt-0.5" />
                <p className="text-xs text-rose-300">{data.error}</p>
              </div>
            </Card>
          )}
        </div>
      </div>
    </div>
  );
}
